"all":
  "children":
    "kubenodes":
      "hosts":
        "farm-0.local":
          "ansible_user": "alex"
        "farm-1.local":
          "ansible_user": "alex"
        "farm-2.local":
          "ansible_user": "alex"
    "personal":
      "hosts":
        "console":
          "ansible_user": "alex"
